name: ❓ Question
description: Template for asking questions
title: "[❓] "
labels:
  - Question
body:
  - type: checkboxes
    id: check-search
    attributes:
      label: Is there an existing issue for this?
      description: >-
        Please search to see if an issue already exists for the issue you
        encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: whats-your-question
    attributes:
      label: What is the your question?
      description: Your question
      placeholder: >-
        Example: How do you know xyz is true?
    validations:
      required: true
