name: 🚀 Enhancement
description: Template for suggesting and enhancement
title: "[🚀] "
labels:
  - Enhancement
body:
  - type: checkboxes
    id: check-search
    attributes:
      label: Is there an existing issue for this?
      description: >-
        Please search to see if an issue already exists for the issue you
        encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    id: check-pull
    attributes:
      label: Will you be opening a pull request?
      description: >-
        Will you be opening a pull request for this enhancement?
      options:
        - label: "yes"
        - label: "no"
  - type: textarea
    id: whats-your-suggestion
    attributes:
      label: What is the your suggested enhancement? and Why is it an enhancement?
      description: Your question
      placeholder: >-
        Example: You should add xyz feature to this work.
    validations:
      required: true
